//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_CRUDTbUsuarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_USUARIOSEntities : DbContext
    {
        public DB_USUARIOSEntities()
            : base("name=DB_USUARIOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<V_USARIOS_INDEX> V_USARIOS_INDEX { get; set; }
    
        public virtual int UDP_USUARIOS_INSERT(string usu_Nambe, string usu_Apellido, string usu_UsuarioAlias, string usu_Contra, Nullable<bool> usu_EsAdmin, Nullable<int> usu_UsuCrea)
        {
            var usu_NambeParameter = usu_Nambe != null ?
                new ObjectParameter("usu_Nambe", usu_Nambe) :
                new ObjectParameter("usu_Nambe", typeof(string));
    
            var usu_ApellidoParameter = usu_Apellido != null ?
                new ObjectParameter("usu_Apellido", usu_Apellido) :
                new ObjectParameter("usu_Apellido", typeof(string));
    
            var usu_UsuarioAliasParameter = usu_UsuarioAlias != null ?
                new ObjectParameter("usu_UsuarioAlias", usu_UsuarioAlias) :
                new ObjectParameter("usu_UsuarioAlias", typeof(string));
    
            var usu_ContraParameter = usu_Contra != null ?
                new ObjectParameter("usu_Contra", usu_Contra) :
                new ObjectParameter("usu_Contra", typeof(string));
    
            var usu_EsAdminParameter = usu_EsAdmin.HasValue ?
                new ObjectParameter("usu_EsAdmin", usu_EsAdmin) :
                new ObjectParameter("usu_EsAdmin", typeof(bool));
    
            var usu_UsuCreaParameter = usu_UsuCrea.HasValue ?
                new ObjectParameter("usu_UsuCrea", usu_UsuCrea) :
                new ObjectParameter("usu_UsuCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_USUARIOS_INSERT", usu_NambeParameter, usu_ApellidoParameter, usu_UsuarioAliasParameter, usu_ContraParameter, usu_EsAdminParameter, usu_UsuCreaParameter);
        }
    
        public virtual ObjectResult<UDP_VALIDAR_LOGIN_Result> UDP_VALIDAR_LOGIN(string usu_Alias, string usu_Contra)
        {
            var usu_AliasParameter = usu_Alias != null ?
                new ObjectParameter("usu_Alias", usu_Alias) :
                new ObjectParameter("usu_Alias", typeof(string));
    
            var usu_ContraParameter = usu_Contra != null ?
                new ObjectParameter("usu_Contra", usu_Contra) :
                new ObjectParameter("usu_Contra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_VALIDAR_LOGIN_Result>("UDP_VALIDAR_LOGIN", usu_AliasParameter, usu_ContraParameter);
        }
    
        public virtual ObjectResult<UDP_ObtenerDatos_Result> UDP_ObtenerDatos(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_ObtenerDatos_Result>("UDP_ObtenerDatos", iDParameter);
        }
    
        public virtual int UDP_EDITAR_USUARIOS(Nullable<int> usu_Id, string usu_Nambe, string usu_Apellido, string usu_UsuarioAlias, Nullable<bool> usu_EsAdmin, Nullable<int> usu_UsuModif)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_NambeParameter = usu_Nambe != null ?
                new ObjectParameter("usu_Nambe", usu_Nambe) :
                new ObjectParameter("usu_Nambe", typeof(string));
    
            var usu_ApellidoParameter = usu_Apellido != null ?
                new ObjectParameter("usu_Apellido", usu_Apellido) :
                new ObjectParameter("usu_Apellido", typeof(string));
    
            var usu_UsuarioAliasParameter = usu_UsuarioAlias != null ?
                new ObjectParameter("usu_UsuarioAlias", usu_UsuarioAlias) :
                new ObjectParameter("usu_UsuarioAlias", typeof(string));
    
            var usu_EsAdminParameter = usu_EsAdmin.HasValue ?
                new ObjectParameter("usu_EsAdmin", usu_EsAdmin) :
                new ObjectParameter("usu_EsAdmin", typeof(bool));
    
            var usu_UsuModifParameter = usu_UsuModif.HasValue ?
                new ObjectParameter("usu_UsuModif", usu_UsuModif) :
                new ObjectParameter("usu_UsuModif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EDITAR_USUARIOS", usu_IdParameter, usu_NambeParameter, usu_ApellidoParameter, usu_UsuarioAliasParameter, usu_EsAdminParameter, usu_UsuModifParameter);
        }
    
        public virtual int UDP_ELIMINAR(Nullable<int> usu_Id, Nullable<int> usu_Modi)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_ModiParameter = usu_Modi.HasValue ?
                new ObjectParameter("usu_Modi", usu_Modi) :
                new ObjectParameter("usu_Modi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_ELIMINAR", usu_IdParameter, usu_ModiParameter);
        }
    }
}
