//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_CRUDTbUsuarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuarios()
        {
            this.tbUsuarios1 = new HashSet<tbUsuarios>();
            this.tbUsuarios11 = new HashSet<tbUsuarios>();
        }
    
        public int usu_Id { get; set; }
        public string usu_Nambe { get; set; }
        public string usu_Apellido { get; set; }
        public string usu_UsuarioAlias { get; set; }
        public string usu_Contra { get; set; }
        public bool usu_EsAdmin { get; set; }
        public int usu_UsuCrea { get; set; }
        public System.DateTime usu_FechaCrea { get; set; }
        public Nullable<int> usu_UsuModif { get; set; }
        public Nullable<System.DateTime> usu_FechaModif { get; set; }
        public bool usu_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios1 { get; set; }
        public virtual tbUsuarios tbUsuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios11 { get; set; }
        public virtual tbUsuarios tbUsuarios3 { get; set; }
    }
}
