//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_CRUDTbUsuarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USARIOS_INDEX
    {
        public int usu_Id { get; set; }
        public string usu_Nambe { get; set; }
        public string usu_Apellido { get; set; }
        public string usu_UsuarioAlias { get; set; }
        public string usu_EsAdmin { get; set; }
    }
}
